version: "2.3"

services:
  control_plane:
    restart: on-failure
    build:
      context: .
      dockerfile: Dockerfile
      target: prod
    volumes:
    - /tmp:/tmp
    - .:/var/run/supergiant
    ports:
    - "8080:8080"
    - "60200-60250:60200-60250"
